
== Regular Expressions in Gnu Awk

Use a RegExp as field separator: echo 'a    b   c' | awk -F'\\s+' '{print $1," ", $2," ",$3}'

=== Gawk specific character classes

\s
Matches any space character as defined by the current locale. 
Think of it as shorthand for ‘[[:space:]]’.

\S
Matches any character that is not a space, as defined by the current locale.
 Think of it as shorthand for ‘[^[:space:]]’.

\w
Matches any word-constituent character—that is, it matches any letter, digit, or underscore.
 Think of it as shorthand for ‘[[:alnum:]_]’.

\W
Matches any character that is not word-constituent.
 Think of it as shorthand for ‘[^[:alnum:]_]’.

\<
Matches the empty string at the beginning of a word. 
For example, /\<away/ matches ‘away’ but not ‘stowaway’.

\>
Matches the empty string at the end of a word. 

For example, /stow\>/ matches ‘stow’ but not ‘stowaway’.

\y
Matches the empty string at either the beginning or the end of a word (i.e., the word boundary).
 For example, ‘\yballs?\y’ matches either ‘ball’ or ‘balls’, as a separate word.

\B
Matches the empty string that occurs between two word-constituent characters.
 For example, /\Brat\B/ matches ‘crate’, but it does not match ‘dirty rat’. ‘\B’ is essentially the opposite of ‘\y’.

There are two other operators that work on buffers. In Emacs, a buffer is, naturally, an Emacs buffer. Other GNU programs, including gawk, consider the entire string to match as the buffer. The operators are:

\`
Matches the empty string at the beginning of a buffer (string)

\'
Matches the empty string at the end of a buffer (string)
